version: "3.7"
services:
  ghar:
    build:
      context: .
      dockerfile: Dockerfile
    image : ghar
    container_name: ghar_container

    ports:
      - "4999:3050"
    env_file:
      - .env
      
    network_mode: host
    
